export const countries = [
  { code: "fr", name: "France" },
  { code: "us", name: "United States" },
  { code: "gb", name: "United Kingdom" },
  { code: "de", name: "Germany" },
  { code: "es", name: "Spain" },
  { code: "it", name: "Italy" },
  { code: "pt", name: "Portugal" },
  { code: "nl", name: "Netherlands" },
  { code: "be", name: "Belgium" },
  { code: "ch", name: "Switzerland" },
  { code: "ca", name: "Canada" },
  { code: "au", name: "Australia" },
  { code: "br", name: "Brazil" },
  { code: "mx", name: "Mexico" },
  { code: "ar", name: "Argentina" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "in", name: "India" },
  { code: "ru", name: "Russia" },
  { code: "pl", name: "Poland" },
  { code: "se", name: "Sweden" },
  { code: "no", name: "Norway" },
  { code: "dk", name: "Denmark" },
  { code: "fi", name: "Finland" },
  { code: "at", name: "Austria" },
  { code: "ie", name: "Ireland" },
  { code: "za", name: "South Africa" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "eg", name: "Egypt" },
  { code: "ma", name: "Morocco" },
  { code: "tn", name: "Tunisia" },
  { code: "dz", name: "Algeria" },
  { code: "tr", name: "Turkey" },
  { code: "sg", name: "Singapore" },
  { code: "hk", name: "Hong Kong" },
  { code: "tw", name: "Taiwan" },
  { code: "th", name: "Thailand" },
  { code: "id", name: "Indonesia" },
  { code: "my", name: "Malaysia" },
] as const;
